nodeLinker: node-modules
npmRegistryServer: 'https://registry.npmjs.org'
enableTelemetry: false
enableGlobalCache: false
compressionLevel: mixed

# Ignore resolution issues with @typescript/lib-dom
packageExtensions:
  eslint-plugin-react-hooks@*:
    peerDependencies:
      eslint: '*'
  '@looker/embed-sdk@*':
    peerDependenciesMeta:
      '@typescript/lib-dom':
        optional: true
