nodeLinker: node-modules
enableGlobalCache: false
compressionLevel: mixed

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  eslint-plugin-react-hooks@*:
    peerDependencies:
      eslint: "*"
